### ISSUE TITLE
PRISMAREAD OFFLINE CAN'T INSTALL FROM GITHUB

### ISSUE THREAD

**Issue by mariofomacajr** [IREA-CNR-MI/prismaread#8]
Nice to meet you!
I can't install prismaread from github. I've done this before, but today prismaread github is offline. There is some action which can be done to solve this issue? I know the development is frozen, but i hope we can continue using this amazing package.
Thank you so much!

**Comment by mariofomacajr** [comment]
Got it!
I've used the devtools package and the same has occured.
But thank you for the suport!
And congratulation for the great job!

**Comment by ranghetti** [comment]
> I've used the devtools package and the same has occured.

Refer to the last comment of the linked resource (https://github.com/r-lib/remotes/issues/210#issuecomment-934661415), not the first.

Thank you
